### ISSUE TITLE
New tag version?

### ISSUE THREAD

**Issue by dotemacs** [mpenet/clojure-snippets#10]
[MELPA stable](http://melpa-stable.milkbox.net/#/) works similarly to MELPA, except(!) it builds it's packages based on git tags.

So maybe once you update this package you can git tag it? Say **1.0.1**? 
This is so that people who use the stable version of your package get the latest changes.

And since you have version number: 

https://github.com/mpenet/clojure-snippets/blob/master/clojure-snippets.el#L7

increment that too. It won't affect the stable package version, but just mentioning it so that you keep them in sync as it's a manual process.

Thank you 😄

**Comment by mpenet** [comment]
done
