### ISSUE TITLE
Some more snippets

### ISSUE THREAD

**Issue by dotemacs** [mpenet/clojure-snippets#11]
What do you think of adding these snippets:

```
# name: cond
# key: cond
# --
(cond
  ($1) $2
  ($3) $4
  :else $5)
```

```
# name: ->
# key: ->
# --
(-> $1
  ($2)
  ($3))
```

```
# name: ->>
# key: ->>
# --
(->> $1
  ($2)
  ($3))
```

**Comment by mpenet** [comment]
Yes for `cond` but do not put the parens around $1 and $3, imho just put single placeholder per cond->result

```
(cond
  $1
  :else $2)
```

About the threading macro I don't think it's that useful. it's very lightweight already and parens wrapping is not always needed (depends on coding style, it's kinda of personal).

Also try to add indentation markers to force indent, like I did in other snippets, it's useful for people who have their own indentation scheme/config.

**Comment by dotemacs** [comment]
Thanks for the feedback, will get to it a bit later...

**Comment by mpenet** [comment]
maybe the `:else` should also be optional/missing, that's usually no so good practice to use it imho (it's an "open case", non exhaustive matching)

**Comment by dotemacs** [comment]
As for `cond`'s `:else`, I agree.

As for not `->` and `->>` not being useful, well both 

* [def](https://github.com/mpenet/clojure-snippets/blob/master/snippets/clojure-mode/def)
* [print](https://github.com/mpenet/clojure-snippets/blob/master/snippets/clojure-mode/print)

are fairly simplistic snippets, but nice to have. Maybe consider adding the threading macros too. I'd be happy to create the PRs if you give me a nod :)

**Comment by mpenet** [comment]
You're right. Anyway it wont hurt anyone as this is optional. *nods*

**Comment by dotemacs** [comment]
Talking about `cond` there's also `condp`: https://github.com/swannodette/clojure-snippets/blob/master/condp

**Comment by dotemacs** [comment]
I'll close this now as it seem that it's mostly resolve or will we resolved with the pending PR
