### ISSUE TITLE
deftype and defrecord expansions contains metadata as the second item?

### ISSUE THREAD

**Issue by jumarko** [mpenet/clojure-snippets#18]
I'm looking at `defr` and `deft` snippets and I'm not sure what's the purpose of `^{"$1"}` expansion.
Should it be used as a documentation?

E.g., If I expand `defr`:

```
(defrecord
    ^{""}
    MyRecord
    []
    )
```

This is not even a valid syntax (I get an "Unmatched delimiter: )" exception).
Since [metadata on records are not supported](https://stackoverflow.com/questions/26454239/documentation-of-records-in-clojure), I'm not sure that that construct meant to represent.

**Comment by mpenet** [comment]
Looks like a mistake. Feel free to send a pr.

**Comment by mpenet** [comment]
fixed in 57aa7abb24b387c18ee7972da56ab82a1bc1528e
