### ISSUE TITLE
imported snippets

### ISSUE THREAD

**Issue by AndreaCrotti** [mpenet/clojure-snippets#6]
Hi,
I hope you don't mind I copied your snippets into the official yasnippet repo, since we don't have them yet and these seem the best out there.

https://github.com/AndreaCrotti/yasnippet-snippets

If you prefer to do a pull request instead I'll revert my change, but anyway either way if I would be very happy if you'd like to keep contributing to that repository..
Thanks

**Comment by mpenet** [comment]
Hi, 

Cool stuff, as for the copying I dont mind as long as there is a reference of it somewhere (text file), if you can add one such refs it would be fine, otherwise I ll prepare a quick PR yes. 

Cheers

**Comment by mpenet** [comment]
Actually the better solution imho would be to use a submodule. it would also save you the burden of updating/diffs etc

**Comment by AndreaCrotti** [comment]
Hi @mpenet, so in theory I agree with you, however:
1. the yasnippet-snippets repository is already a submodule of yasnippet, so adding another level might make it messy.
2. yasnippet-snippets repository is really just though as a drop-in with everything self contained (there are no other submodules at the moment)

Every pull request done there gets merged very quickly and it's easier to get contributors if there is only one project imho..
So if you don't mind for me the best thing would be to do a commit where:
1. you delete the existing clojure-mode snippets that I imported (just leave the .yas-parents file though please).
2. you copy over your snippets and do a PR..

Let me know what you think,
Thanks a lot

**Comment by mpenet** [comment]
bah, let's go like this, I dont really care after all, and there was no license anywhere. Thanks
